// DEMO DATA STORE FOR FEMS FABRICATION & PURCHASE SYSTEM
import { subMonths } from "date-fns";

export interface Product {
  id: string;
  name: string;
  code: string;
  description: string;
  active: boolean;
}

export interface Material {
  material_id: string;
  id: string;
  name: string;
  code: string;
  uom: string;
  total_purchased: number;
  total_consumed: number;
  current_stock: number;
  minimum_stock: number;
  status: "healthy" | "low" | "critical";
  active: boolean;
}

// Helper to generate dynamic relative dates matching current year & month
const getRelDate = (monthsAgo: number, day: number = 15): string => {
  const d = subMonths(new Date(), monthsAgo);
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(Math.min(day, 28)).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
};

export const DEMO_PRODUCTS: Product[] = [
  { id: "p-1", name: "Table", code: "PROD-TBL-01", description: "Standard Worktable / ESD Assembly Bench", active: true },
  { id: "p-2", name: "Rack", code: "PROD-RCK-02", description: "Heavy Duty Pipe & Flow Rack", active: true },
  { id: "p-3", name: "Trolley", code: "PROD-TRL-03", description: "Material Handling & Kitting Trolley", active: true },
  { id: "p-4", name: "Stand", code: "PROD-STD-04", description: "Ergonomic Display & Inspection Stand", active: true }
];

// 24 Standard Industry Materials Catalog
export const DEMO_MATERIALS: Material[] = [
  { material_id: "m-1", id: "m-1", name: "40 TYPE PLACON ROLLER", code: "PLACON-40", uom: "MTR", total_purchased: 4500, total_consumed: 3200, current_stock: 1300, minimum_stock: 500, status: "healthy", active: true },
  { material_id: "m-2", id: "m-2", name: "80 TYPE PLACON ROLLER", code: "PLACON-80", uom: "MTR", total_purchased: 3800, total_consumed: 2900, current_stock: 900, minimum_stock: 400, status: "healthy", active: true },
  { material_id: "m-3", id: "m-3", name: "40 TYPE A1 JOINT", code: "GPA40", uom: "PCS", total_purchased: 8500, total_consumed: 6100, current_stock: 2400, minimum_stock: 800, status: "healthy", active: true },
  { material_id: "m-4", id: "m-4", name: "80 TYPE A1 JOINT", code: "GPA80", uom: "PCS", total_purchased: 6200, total_consumed: 4800, current_stock: 1400, minimum_stock: 600, status: "healthy", active: true },
  { material_id: "m-5", id: "m-5", name: "40 TYPE B2 JOINT", code: "GPB40", uom: "PCS", total_purchased: 7400, total_consumed: 5300, current_stock: 2100, minimum_stock: 750, status: "healthy", active: true },
  { material_id: "m-6", id: "m-6", name: "80 TYPE B2 JOINT", code: "GPB80", uom: "PCS", total_purchased: 5900, total_consumed: 4400, current_stock: 1500, minimum_stock: 550, status: "healthy", active: true },

  { material_id: "m-7", id: "m-7", name: "PJ1", code: "PJ1", uom: "SET", total_purchased: 12000, total_consumed: 9500, current_stock: 2500, minimum_stock: 1000, status: "healthy", active: true },
  { material_id: "m-8", id: "m-8", name: "P100 JOINT", code: "P100", uom: "SET", total_purchased: 3500, total_consumed: 2800, current_stock: 700, minimum_stock: 300, status: "healthy", active: true },
  { material_id: "m-9", id: "m-9", name: "PJ14 JOINT", code: "PJ14", uom: "SET", total_purchased: 4200, total_consumed: 3400, current_stock: 800, minimum_stock: 350, status: "healthy", active: true },
  { material_id: "m-10", id: "m-10", name: "PJ16 JOINT", code: "PJ16", uom: "SET", total_purchased: 3100, total_consumed: 2650, current_stock: 450, minimum_stock: 500, status: "low", active: true },
  { material_id: "m-11", id: "m-11", name: "PJ18 JOINT", code: "PJ18", uom: "SET", total_purchased: 2800, total_consumed: 2620, current_stock: 180, minimum_stock: 400, status: "critical", active: true },
  { material_id: "m-12", id: "m-12", name: "PJ2 JOINT", code: "PJ2", uom: "SET", total_purchased: 9800, total_consumed: 7200, current_stock: 2600, minimum_stock: 900, status: "healthy", active: true },
  { material_id: "m-13", id: "m-13", name: "PJ3 JOINT", code: "PJ3", uom: "SET", total_purchased: 5100, total_consumed: 4100, current_stock: 1000, minimum_stock: 500, status: "healthy", active: true },
  { material_id: "m-14", id: "m-14", name: "PJ4 JOINT", code: "PJ4", uom: "SET", total_purchased: 4700, total_consumed: 3900, current_stock: 800, minimum_stock: 450, status: "healthy", active: true },
  { material_id: "m-15", id: "m-15", name: "PJ5 JOINT", code: "PJ5", uom: "SET", total_purchased: 3900, total_consumed: 3200, current_stock: 700, minimum_stock: 350, status: "healthy", active: true },
  { material_id: "m-16", id: "m-16", name: "PJ7 JOINT", code: "PJ7", uom: "SET", total_purchased: 3600, total_consumed: 3100, current_stock: 500, minimum_stock: 400, status: "healthy", active: true },
  { material_id: "m-17", id: "m-17", name: "PJ8 JOINT", code: "PJ8", uom: "SET", total_purchased: 3400, total_consumed: 2900, current_stock: 500, minimum_stock: 350, status: "healthy", active: true },

  { material_id: "m-18", id: "m-18", name: "SS PIPE", code: "SS-PIPE-28", uom: "MTR", total_purchased: 15000, total_consumed: 11200, current_stock: 3800, minimum_stock: 1500, status: "healthy", active: true },
  { material_id: "m-19", id: "m-19", name: "6X2 PU WHEEL SWIVEL LOCK", code: "WHL-6X2-SL", uom: "PCS", total_purchased: 2400, total_consumed: 1800, current_stock: 600, minimum_stock: 300, status: "healthy", active: true },
  { material_id: "m-20", id: "m-20", name: "6X2 PU WHEEL FIXED", code: "WHL-6X2-FX", uom: "PCS", total_purchased: 2200, total_consumed: 1700, current_stock: 500, minimum_stock: 250, status: "healthy", active: true },
  { material_id: "m-21", id: "m-21", name: "3x1.25 PU WHEEL SWIVEL", code: "WHL-3X1-SW", uom: "PCS", total_purchased: 3100, total_consumed: 2780, current_stock: 320, minimum_stock: 350, status: "low", active: true },
  { material_id: "m-22", id: "m-22", name: "3x1.25 PU WHEEL SWIVEL LOCK", code: "WHL-3X1-SL", uom: "PCS", total_purchased: 2900, total_consumed: 2300, current_stock: 600, minimum_stock: 300, status: "healthy", active: true },
  { material_id: "m-23", id: "m-23", name: "END CAP", code: "END-CAP-28", uom: "PCS", total_purchased: 18000, total_consumed: 13500, current_stock: 4500, minimum_stock: 2000, status: "healthy", active: true },
  { material_id: "m-24", id: "m-24", name: "PJ15 JOINT", code: "PJ15", uom: "SET", total_purchased: 3300, total_consumed: 2700, current_stock: 600, minimum_stock: 300, status: "healthy", active: true }
];

// 14 Standard Manufacturing Plant Departments
export const DEMO_DEPARTMENTS = [
  { id: "dept-1", name: "Fabrication", description: "Sheet Metal Cutting, Bending, Welding & Structural Fabrication" },
  { id: "dept-2", name: "Assembly", description: "Line Assembly, Sub-assembly & Mechanical Fitting" },
  { id: "dept-3", name: "Quality Assurance & Control (QA/QC)", description: "Raw Material Inspection, In-Process QC & Final PDI Inspection" },
  { id: "dept-4", name: "Innovation & R&D", description: "Product Design, CAD/CAM Prototyping & Process Engineering" },
  { id: "dept-5", name: "Production Planning & Control (PPC)", description: "Scheduling, Work Order Dispatch & Capacity Planning" },
  { id: "dept-6", name: "Stores & Warehouse", description: "Raw Material Inwarding, Kitting & Finished Goods Inventory" },
  { id: "dept-7", name: "Purchase & Procurement", description: "Vendor Management, Material Sourcing & Purchase Orders" },
  { id: "dept-8", name: "Maintenance & Engineering", description: "Machine Maintenance, Preventive Checks & Facility Engineering" },
  { id: "dept-9", name: "Toolroom & Jig/Fixture", description: "Die Repair, Custom Tooling, Jigs & Fixtures Maintenance" },
  { id: "dept-10", name: "Surface Finishing & Paint Shop", description: "Powder Coating, Electroplating & Surface Pre-treatment" },
  { id: "dept-11", name: "Dispatch & Logistics", description: "Packaging, Shipping, E-Way Bill & Freight Management" },
  { id: "dept-12", name: "Environment, Health & Safety (EHS)", description: "Industrial Safety, PPE Compliance & Waste Management" },
  { id: "dept-13", name: "Finance & Accounts", description: "Material Costing, Invoicing, Vendor Payments & Auditing" },
  { id: "dept-14", name: "Human Resources & Admin", description: "Workforce Planning, Operator Attendance & Plant Security" }
];

// 60 REALISTIC DUMMY FABRICATION ENTRIES ASSIGNED TO BHIWADI (NGM & PGTL PLANTS)
export const DEMO_FABRICATIONS = [
  // Month 0 (Current Month - Jul 2026)
  { id: "fab-1", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: getRelDate(0, 27), product_quantity: 25, supervisor_name: "Ramesh Sharma", remarks: "Standard Worktables Batch", products: { name: "Table" }, departments: { name: "Fabrication" } },
  { id: "fab-2", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: getRelDate(0, 24), product_quantity: 18, supervisor_name: "Amit Kumar", remarks: "Heavy Flow Racks", products: { name: "Rack" }, departments: { name: "Assembly" } },
  { id: "fab-3", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: getRelDate(0, 21), product_quantity: 22, supervisor_name: "Suresh Singh", remarks: "Parts Kitting Trolley", products: { name: "Trolley" }, departments: { name: "Fabrication" } },
  { id: "fab-4", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: getRelDate(0, 18), product_quantity: 12, supervisor_name: "Vikas Verma", remarks: "Display Stands Prototype", products: { name: "Stand" }, departments: { name: "Innovation & R&D" } },
  { id: "fab-5", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: getRelDate(0, 15), product_quantity: 20, supervisor_name: "Rajesh Patel", remarks: "ESD Assembly Line Tables", products: { name: "Table" }, departments: { name: "Assembly" } },
  { id: "fab-6", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: getRelDate(0, 12), product_quantity: 16, supervisor_name: "Pankaj Sharma", remarks: "Sub-assembly Trolleys", products: { name: "Trolley" }, departments: { name: "Assembly" } },
  { id: "fab-7", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: getRelDate(0, 9), product_quantity: 14, supervisor_name: "Deepak Joshi", remarks: "FIFO Gravity Flow Racks", products: { name: "Rack" }, departments: { name: "Production Planning & Control (PPC)" } },
  { id: "fab-8", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: getRelDate(0, 6), product_quantity: 19, supervisor_name: "Manoj Verma", remarks: "Quality Audit Workstation", products: { name: "Table" }, departments: { name: "Quality Assurance & Control (QA/QC)" } },
  { id: "fab-9", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: getRelDate(0, 3), product_quantity: 10, supervisor_name: "Ramesh Sharma", remarks: "Tool Holding Racks", products: { name: "Rack" }, departments: { name: "Fabrication" } },

  // Month 1 (Jun 2026)
  { id: "fab-10", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-06-29", product_quantity: 28, supervisor_name: "Pankaj Sharma", remarks: "Kitting Trolley Assembly", products: { name: "Trolley" }, departments: { name: "Assembly" } },
  { id: "fab-11", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-06-26", product_quantity: 32, supervisor_name: "Ramesh Sharma", remarks: "Modular Pipe Workbenches", products: { name: "Table" }, departments: { name: "Fabrication" } },
  { id: "fab-12", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-06-23", product_quantity: 24, supervisor_name: "Amit Kumar", remarks: "FIFO Pallet Flow Racks", products: { name: "Rack" }, departments: { name: "Production Planning & Control (PPC)" } },
  { id: "fab-13", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-06-20", product_quantity: 18, supervisor_name: "Suresh Singh", remarks: "Component Storage Stands", products: { name: "Stand" }, departments: { name: "Quality Assurance & Control (QA/QC)" } },
  { id: "fab-14", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-06-17", product_quantity: 21, supervisor_name: "Vikas Verma", remarks: "Assembly Fitting Tables", products: { name: "Table" }, departments: { name: "Assembly" } },
  { id: "fab-15", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-06-14", product_quantity: 15, supervisor_name: "Rajesh Patel", remarks: "Store Materials Trolley", products: { name: "Trolley" }, departments: { name: "Fabrication" } },
  { id: "fab-16", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-06-11", product_quantity: 17, supervisor_name: "Deepak Joshi", remarks: "Testing Jig Stands", products: { name: "Stand" }, departments: { name: "Innovation & R&D" } },
  { id: "fab-17", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-06-08", product_quantity: 23, supervisor_name: "Manoj Verma", remarks: "Heavy Storage Racks", products: { name: "Rack" }, departments: { name: "Fabrication" } },
  { id: "fab-18", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-06-05", product_quantity: 12, supervisor_name: "Ramesh Sharma", remarks: "ESD Worktables", products: { name: "Table" }, departments: { name: "Assembly" } },
  { id: "fab-19", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-06-02", product_quantity: 29, supervisor_name: "Vikas Verma", remarks: "High-Capacity Pipe Flow Racks", products: { name: "Rack" }, departments: { name: "Fabrication" } },

  // Month 2 (May 2026)
  { id: "fab-20", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-05-30", product_quantity: 34, supervisor_name: "Vikas Verma", remarks: "Assembly Line Workbenches", products: { name: "Table" }, departments: { name: "Assembly" } },
  { id: "fab-21", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-05-27", product_quantity: 29, supervisor_name: "Rajesh Patel", remarks: "Heavy Storage Flow Racks", products: { name: "Rack" }, departments: { name: "Fabrication" } },
  { id: "fab-22", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-05-24", product_quantity: 38, supervisor_name: "Pankaj Sharma", remarks: "Plant Material Trolleys", products: { name: "Trolley" }, departments: { name: "Fabrication" } },
  { id: "fab-23", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-05-21", product_quantity: 25, supervisor_name: "Ramesh Sharma", remarks: "R&D Ergonomic Stands", products: { name: "Stand" }, departments: { name: "Innovation & R&D" } },
  { id: "fab-24", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-05-18", product_quantity: 19, supervisor_name: "Amit Kumar", remarks: "PPC Scheduling Workstation", products: { name: "Table" }, departments: { name: "Production Planning & Control (PPC)" } },
  { id: "fab-25", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-05-15", product_quantity: 22, supervisor_name: "Suresh Singh", remarks: "QA Inspection Bench", products: { name: "Table" }, departments: { name: "Quality Assurance & Control (QA/QC)" } },
  { id: "fab-26", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-05-12", product_quantity: 17, supervisor_name: "Deepak Joshi", remarks: "Part Picking Trolleys", products: { name: "Trolley" }, departments: { name: "Assembly" } },
  { id: "fab-27", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-05-09", product_quantity: 14, supervisor_name: "Manoj Verma", remarks: "Toolroom Racks", products: { name: "Rack" }, departments: { name: "Fabrication" } },
  { id: "fab-28", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-05-06", product_quantity: 31, supervisor_name: "Amit Kumar", remarks: "ESD Grounded Tables", products: { name: "Table" }, departments: { name: "Assembly" } },
  { id: "fab-29", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-05-03", product_quantity: 26, supervisor_name: "Pankaj Sharma", remarks: "Heavy Flow Gravity Racks", products: { name: "Rack" }, departments: { name: "Fabrication" } },

  // Month 3 (Apr 2026)
  { id: "fab-30", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-04-29", product_quantity: 28, supervisor_name: "Amit Kumar", remarks: "Placon Roller Track Tables", products: { name: "Table" }, departments: { name: "Assembly" } },
  { id: "fab-31", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-04-26", product_quantity: 24, supervisor_name: "Suresh Singh", remarks: "Slanted Flow Racks", products: { name: "Rack" }, departments: { name: "Production Planning & Control (PPC)" } },
  { id: "fab-32", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-04-23", product_quantity: 36, supervisor_name: "Vikas Verma", remarks: "Sub-assembly Kitting Trolleys", products: { name: "Trolley" }, departments: { name: "Fabrication" } },
  { id: "fab-33", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-04-20", product_quantity: 22, supervisor_name: "Rajesh Patel", remarks: "Quality Inspection Stands", products: { name: "Stand" }, departments: { name: "Quality Assurance & Control (QA/QC)" } },
  { id: "fab-34", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-04-17", product_quantity: 18, supervisor_name: "Pankaj Sharma", remarks: "ESD Benches Batch", products: { name: "Table" }, departments: { name: "Assembly" } },
  { id: "fab-35", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-04-14", product_quantity: 20, supervisor_name: "Deepak Joshi", remarks: "Heavy Pipe Racks", products: { name: "Rack" }, departments: { name: "Fabrication" } },
  { id: "fab-36", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-04-11", product_quantity: 15, supervisor_name: "Manoj Verma", remarks: "Handling Trolley Batch", products: { name: "Trolley" }, departments: { name: "Assembly" } },
  { id: "fab-37", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-04-08", product_quantity: 12, supervisor_name: "Ramesh Sharma", remarks: "Prototype Test Stand", products: { name: "Stand" }, departments: { name: "Innovation & R&D" } },
  { id: "fab-38", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-04-05", product_quantity: 33, supervisor_name: "Suresh Singh", remarks: "Main Line Heavy Workstations", products: { name: "Table" }, departments: { name: "Fabrication" } },
  { id: "fab-39", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-04-02", product_quantity: 27, supervisor_name: "Rajesh Patel", remarks: "Mobile Assembly Trolleys", products: { name: "Trolley" }, departments: { name: "Assembly" } },

  // Month 4 (Mar 2026)
  { id: "fab-40", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-03-30", product_quantity: 26, supervisor_name: "Pankaj Sharma", remarks: "Packing Workbenches", products: { name: "Table" }, departments: { name: "Fabrication" } },
  { id: "fab-41", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-03-27", product_quantity: 20, supervisor_name: "Ramesh Sharma", remarks: "Pipe Storage Racks", products: { name: "Rack" }, departments: { name: "Assembly" } },
  { id: "fab-42", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-03-24", product_quantity: 30, supervisor_name: "Amit Kumar", remarks: "Warehouse Material Trolleys", products: { name: "Trolley" }, departments: { name: "Assembly" } },
  { id: "fab-43", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-03-21", product_quantity: 16, supervisor_name: "Suresh Singh", remarks: "Sub-assembly Jig Stand", products: { name: "Stand" }, departments: { name: "Fabrication" } },
  { id: "fab-44", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-03-18", product_quantity: 22, supervisor_name: "Vikas Verma", remarks: "Operator ESD Benches", products: { name: "Table" }, departments: { name: "Assembly" } },
  { id: "fab-45", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-03-15", product_quantity: 18, supervisor_name: "Rajesh Patel", remarks: "Flow Rack System", products: { name: "Rack" }, departments: { name: "Production Planning & Control (PPC)" } },
  { id: "fab-46", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-03-12", product_quantity: 25, supervisor_name: "Deepak Joshi", remarks: "Factory Kitting Trolleys", products: { name: "Trolley" }, departments: { name: "Fabrication" } },
  { id: "fab-47", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-03-09", product_quantity: 14, supervisor_name: "Manoj Verma", remarks: "QA Meter Stands", products: { name: "Stand" }, departments: { name: "Quality Assurance & Control (QA/QC)" } },
  { id: "fab-48", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-03-06", product_quantity: 29, supervisor_name: "Amit Kumar", remarks: "Pipe Storage Heavy Racks", products: { name: "Rack" }, departments: { name: "Fabrication" } },
  { id: "fab-49", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-03-03", product_quantity: 35, supervisor_name: "Ramesh Sharma", remarks: "ESD Worktable Batch", products: { name: "Table" }, departments: { name: "Assembly" } },

  // Month 5 (Feb 2026)
  { id: "fab-50", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-02-28", product_quantity: 20, supervisor_name: "Suresh Singh", remarks: "ESD Testing Benches", products: { name: "Table" }, departments: { name: "Innovation & R&D" } },
  { id: "fab-51", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-02-25", product_quantity: 16, supervisor_name: "Vikas Verma", remarks: "Component Sorting Racks", products: { name: "Rack" }, departments: { name: "Fabrication" } },
  { id: "fab-52", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-02-22", product_quantity: 22, supervisor_name: "Rajesh Patel", remarks: "Sub-assembly Trolley Batch", products: { name: "Trolley" }, departments: { name: "Assembly" } },
  { id: "fab-53", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-02-19", product_quantity: 15, supervisor_name: "Pankaj Sharma", remarks: "Mobile Inspection Stand", products: { name: "Stand" }, departments: { name: "Quality Assurance & Control (QA/QC)" } },
  { id: "fab-54", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-02-16", product_quantity: 24, supervisor_name: "Ramesh Sharma", remarks: "Heavy Duty Worktable", products: { name: "Table" }, departments: { name: "Fabrication" } },
  { id: "fab-55", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-02-13", product_quantity: 19, supervisor_name: "Amit Kumar", remarks: "Slanted Storage Racks", products: { name: "Rack" }, departments: { name: "Assembly" } },
  { id: "fab-56", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-02-10", product_quantity: 21, supervisor_name: "Deepak Joshi", remarks: "Trolley Frame Batch", products: { name: "Trolley" }, departments: { name: "Fabrication" } },
  { id: "fab-57", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-02-07", product_quantity: 13, supervisor_name: "Manoj Verma", remarks: "R&D Prototype Stand", products: { name: "Stand" }, departments: { name: "Innovation & R&D" } },
  { id: "fab-58", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", fab_date: "2026-02-04", product_quantity: 30, supervisor_name: "Suresh Singh", remarks: "Assembly Workbenches", products: { name: "Table" }, departments: { name: "Assembly" } },
  { id: "fab-59", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", fab_date: "2026-02-02", product_quantity: 28, supervisor_name: "Vikas Verma", remarks: "Flow Rack System Batch", products: { name: "Rack" }, departments: { name: "Fabrication" } }
];

// 60 REALISTIC DUMMY PURCHASE ORDERS ASSIGNED TO BHIWADI (NGM & PGTL PLANTS)
export const DEMO_PURCHASES = [
  // Month 0 (Jul 2026)
  { po_id: "po-1", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: getRelDate(0, 27), po_number: "PO-2026-099", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-18", material_name: "SS PIPE", uom: "MTR", po_quantity: 2000, received_quantity: 2000, pending_quantity: 0 },
  { po_id: "po-2", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: getRelDate(0, 27), po_number: "PO-2026-099", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-23", material_name: "END CAP", uom: "PCS", po_quantity: 1000, received_quantity: 1000, pending_quantity: 0 },
  { po_id: "po-3", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: getRelDate(0, 24), po_number: "PO-2026-098", supplier_name: "Vikas Industrial Supplies", material_id: "m-7", material_name: "PJ1", uom: "SET", po_quantity: 1500, received_quantity: 1500, pending_quantity: 0 },
  { po_id: "po-4", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: getRelDate(0, 24), po_number: "PO-2026-098", supplier_name: "Vikas Industrial Supplies", material_id: "m-12", material_name: "PJ2 JOINT", uom: "SET", po_quantity: 1200, received_quantity: 1200, pending_quantity: 0 },
  { po_id: "po-5", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: getRelDate(0, 20), po_number: "PO-2026-097", supplier_name: "Apex Hardware Corp", material_id: "m-1", material_name: "40 TYPE PLACON ROLLER", uom: "MTR", po_quantity: 800, received_quantity: 800, pending_quantity: 0 },
  { po_id: "po-6", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: getRelDate(0, 20), po_number: "PO-2026-097", supplier_name: "Apex Hardware Corp", material_id: "m-3", material_name: "40 TYPE A1 JOINT", uom: "PCS", po_quantity: 1500, received_quantity: 1500, pending_quantity: 0 },
  { po_id: "po-7", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: getRelDate(0, 15), po_number: "PO-2026-096", supplier_name: "Precision Tools Co", material_id: "m-19", material_name: "6X2 PU WHEEL SWIVEL LOCK", uom: "PCS", po_quantity: 400, received_quantity: 400, pending_quantity: 0 },
  { po_id: "po-8", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: getRelDate(0, 10), po_number: "PO-2026-095", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-2", material_name: "80 TYPE PLACON ROLLER", uom: "MTR", po_quantity: 600, received_quantity: 600, pending_quantity: 0 },
  { po_id: "po-9", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: getRelDate(0, 5), po_number: "PO-2026-094", supplier_name: "Star Fasteners Ltd", material_id: "m-8", material_name: "P100 JOINT", uom: "SET", po_quantity: 500, received_quantity: 500, pending_quantity: 0 },

  // Month 1 (Jun 2026)
  { po_id: "po-10", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-06-29", po_number: "PO-2026-089", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-18", material_name: "SS PIPE", uom: "MTR", po_quantity: 2500, received_quantity: 2500, pending_quantity: 0 },
  { po_id: "po-11", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-06-26", po_number: "PO-2026-089", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-7", material_name: "PJ1", uom: "SET", po_quantity: 2000, received_quantity: 2000, pending_quantity: 0 },
  { po_id: "po-12", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-06-23", po_number: "PO-2026-088", supplier_name: "Vikas Industrial Supplies", material_id: "m-4", material_name: "80 TYPE A1 JOINT", uom: "PCS", po_quantity: 1800, received_quantity: 1800, pending_quantity: 0 },
  { po_id: "po-13", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-06-20", po_number: "PO-2026-087", supplier_name: "Apex Hardware Corp", material_id: "m-6", material_name: "80 TYPE B2 JOINT", uom: "PCS", po_quantity: 1400, received_quantity: 1400, pending_quantity: 0 },
  { po_id: "po-14", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-06-17", po_number: "PO-2026-086", supplier_name: "Precision Tools Co", material_id: "m-20", material_name: "6X2 PU WHEEL FIXED", uom: "PCS", po_quantity: 500, received_quantity: 500, pending_quantity: 0 },
  { po_id: "po-15", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-06-14", po_number: "PO-2026-085", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-23", material_name: "END CAP", uom: "PCS", po_quantity: 2500, received_quantity: 2500, pending_quantity: 0 },
  { po_id: "po-16", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-06-11", po_number: "PO-2026-084", supplier_name: "Star Fasteners Ltd", material_id: "m-12", material_name: "PJ2 JOINT", uom: "SET", po_quantity: 1500, received_quantity: 1500, pending_quantity: 0 },
  { po_id: "po-17", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-06-08", po_number: "PO-2026-083", supplier_name: "Vikas Industrial Supplies", material_id: "m-2", material_name: "80 TYPE PLACON ROROLLER", uom: "MTR", po_quantity: 800, received_quantity: 800, pending_quantity: 0 },
  { po_id: "po-18", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-06-05", po_number: "PO-2026-082", supplier_name: "Apex Hardware Corp", material_id: "m-5", material_name: "40 TYPE B2 JOINT", uom: "PCS", po_quantity: 1200, received_quantity: 1200, pending_quantity: 0 },
  { po_id: "po-19", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-06-02", po_number: "PO-2026-081", supplier_name: "Precision Tools Co", material_id: "m-18", material_name: "SS PIPE", uom: "MTR", po_quantity: 2200, received_quantity: 2200, pending_quantity: 0 },

  // Month 2 (May 2026)
  { po_id: "po-20", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-05-29", po_number: "PO-2026-078", supplier_name: "Precision Tools Co", material_id: "m-18", material_name: "SS PIPE", uom: "MTR", po_quantity: 3000, received_quantity: 3000, pending_quantity: 0 },
  { po_id: "po-21", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-05-26", po_number: "PO-2026-077", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-7", material_name: "PJ1", uom: "SET", po_quantity: 2500, received_quantity: 2500, pending_quantity: 0 },
  { po_id: "po-22", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-05-23", po_number: "PO-2026-076", supplier_name: "Vikas Industrial Supplies", material_id: "m-1", material_name: "40 TYPE PLACON ROLLER", uom: "MTR", po_quantity: 1000, received_quantity: 1000, pending_quantity: 0 },
  { po_id: "po-23", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-05-20", po_number: "PO-2026-075", supplier_name: "Apex Hardware Corp", material_id: "m-3", material_name: "40 TYPE A1 JOINT", uom: "PCS", po_quantity: 2000, received_quantity: 2000, pending_quantity: 0 },
  { po_id: "po-24", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-05-17", po_number: "PO-2026-074", supplier_name: "Star Fasteners Ltd", material_id: "m-21", material_name: "3x1.25 PU WHEEL SWIVEL", uom: "PCS", po_quantity: 600, received_quantity: 600, pending_quantity: 0 },
  { po_id: "po-25", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-05-14", po_number: "PO-2026-073", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-23", material_name: "END CAP", uom: "PCS", po_quantity: 3000, received_quantity: 3000, pending_quantity: 0 },
  { po_id: "po-26", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-05-11", po_number: "PO-2026-072", supplier_name: "Precision Tools Co", material_id: "m-15", material_name: "PJ5 JOINT", uom: "SET", po_quantity: 800, received_quantity: 800, pending_quantity: 0 },
  { po_id: "po-27", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-05-08", po_number: "PO-2026-071", supplier_name: "Vikas Industrial Supplies", material_id: "m-13", material_name: "PJ3 JOINT", uom: "SET", po_quantity: 1000, received_quantity: 1000, pending_quantity: 0 },
  { po_id: "po-28", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-05-05", po_number: "PO-2026-070", supplier_name: "Apex Hardware Corp", material_id: "m-8", material_name: "P100 JOINT", uom: "SET", po_quantity: 1200, received_quantity: 1200, pending_quantity: 0 },
  { po_id: "po-29", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-05-02", po_number: "PO-2026-069", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-18", material_name: "SS PIPE", uom: "MTR", po_quantity: 2800, received_quantity: 2800, pending_quantity: 0 },

  // Month 3 (Apr 2026)
  { po_id: "po-30", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-04-29", po_number: "PO-2026-065", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-18", material_name: "SS PIPE", uom: "MTR", po_quantity: 2200, received_quantity: 2200, pending_quantity: 0 },
  { po_id: "po-31", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-04-26", po_number: "PO-2026-064", supplier_name: "Apex Hardware Corp", material_id: "m-2", material_name: "80 TYPE PLACON ROLLER", uom: "MTR", po_quantity: 900, received_quantity: 900, pending_quantity: 0 },
  { po_id: "po-32", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-04-23", po_number: "PO-2026-063", supplier_name: "Vikas Industrial Supplies", material_id: "m-4", material_name: "80 TYPE A1 JOINT", uom: "PCS", po_quantity: 1600, received_quantity: 1600, pending_quantity: 0 },
  { po_id: "po-33", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-04-20", po_number: "PO-2026-062", supplier_name: "Precision Tools Co", material_id: "m-7", material_name: "PJ1", uom: "SET", po_quantity: 1800, received_quantity: 1800, pending_quantity: 0 },
  { po_id: "po-34", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-04-17", po_number: "PO-2026-061", supplier_name: "Star Fasteners Ltd", material_id: "m-12", material_name: "PJ2 JOINT", uom: "SET", po_quantity: 1400, received_quantity: 1400, pending_quantity: 0 },
  { po_id: "po-35", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-04-14", po_number: "PO-2026-060", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-23", material_name: "END CAP", uom: "PCS", po_quantity: 2000, received_quantity: 2000, pending_quantity: 0 },
  { po_id: "po-36", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-04-11", po_number: "PO-2026-059", supplier_name: "Vikas Industrial Supplies", material_id: "m-14", material_name: "PJ4 JOINT", uom: "SET", po_quantity: 700, received_quantity: 700, pending_quantity: 0 },
  { po_id: "po-37", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-04-08", po_number: "PO-2026-058", supplier_name: "Apex Hardware Corp", material_id: "m-16", material_name: "PJ7 JOINT", uom: "SET", po_quantity: 600, received_quantity: 600, pending_quantity: 0 },
  { po_id: "po-38", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-04-05", po_number: "PO-2026-057", supplier_name: "Precision Tools Co", material_id: "m-1", material_name: "40 TYPE PLACON ROLLER", uom: "MTR", po_quantity: 1100, received_quantity: 1100, pending_quantity: 0 },
  { po_id: "po-39", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-04-02", po_number: "PO-2026-056", supplier_name: "Star Fasteners Ltd", material_id: "m-3", material_name: "40 TYPE A1 JOINT", uom: "PCS", po_quantity: 1700, received_quantity: 1700, pending_quantity: 0 },

  // Month 4 (Mar 2026)
  { po_id: "po-40", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-03-29", po_number: "PO-2026-052", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-18", material_name: "SS PIPE", uom: "MTR", po_quantity: 2800, received_quantity: 2800, pending_quantity: 0 },
  { po_id: "po-41", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-03-26", po_number: "PO-2026-051", supplier_name: "Vikas Industrial Supplies", material_id: "m-1", material_name: "40 TYPE PLACON ROLLER", uom: "MTR", po_quantity: 1100, received_quantity: 1100, pending_quantity: 0 },
  { po_id: "po-42", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-03-23", po_number: "PO-2026-050", supplier_name: "Precision Tools Co", material_id: "m-3", material_name: "40 TYPE A1 JOINT", uom: "PCS", po_quantity: 2200, received_quantity: 2200, pending_quantity: 0 },
  { po_id: "po-43", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-03-20", po_number: "PO-2026-049", supplier_name: "Apex Hardware Corp", material_id: "m-5", material_name: "40 TYPE B2 JOINT", uom: "PCS", po_quantity: 1800, received_quantity: 1800, pending_quantity: 0 },
  { po_id: "po-44", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-03-17", po_number: "PO-2026-048", supplier_name: "Star Fasteners Ltd", material_id: "m-7", material_name: "PJ1", uom: "SET", po_quantity: 2000, received_quantity: 2000, pending_quantity: 0 },
  { po_id: "po-45", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-03-14", po_number: "PO-2026-047", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-23", material_name: "END CAP", uom: "PCS", po_quantity: 2800, received_quantity: 2800, pending_quantity: 0 },
  { po_id: "po-46", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-03-11", po_number: "PO-2026-046", supplier_name: "Vikas Industrial Supplies", material_id: "m-19", material_name: "6X2 PU WHEEL SWIVEL LOCK", uom: "PCS", po_quantity: 500, received_quantity: 500, pending_quantity: 0 },
  { po_id: "po-47", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-03-08", po_number: "PO-2026-045", supplier_name: "Apex Hardware Corp", material_id: "m-9", material_name: "PJ14 JOINT", uom: "SET", po_quantity: 750, received_quantity: 750, pending_quantity: 0 },
  { po_id: "po-48", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-03-05", po_number: "PO-2026-044", supplier_name: "Precision Tools Co", material_id: "m-12", material_name: "PJ2 JOINT", uom: "SET", po_quantity: 1600, received_quantity: 1600, pending_quantity: 0 },
  { po_id: "po-49", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-03-02", po_number: "PO-2026-043", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-2", material_name: "80 TYPE PLACON ROLLER", uom: "MTR", po_quantity: 950, received_quantity: 950, pending_quantity: 0 },

  // Month 5 (Feb 2026)
  { po_id: "po-50", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-02-28", po_number: "4500029185", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-2", material_name: "80 TYPE PLACON ROLLER", uom: "MTR", po_quantity: 124, received_quantity: 124, pending_quantity: 0 },
  { po_id: "po-51", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-02-25", po_number: "4500029185", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-1", material_name: "40 TYPE PLACON ROLLER", uom: "MTR", po_quantity: 124, received_quantity: 124, pending_quantity: 0 },
  { po_id: "po-52", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-02-22", po_number: "4500029185", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-4", material_name: "80 TYPE A1 JOINT", uom: "PCS", po_quantity: 500, received_quantity: 500, pending_quantity: 0 },
  { po_id: "po-53", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-02-19", po_number: "4800001811", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-7", material_name: "PJ1", uom: "SET", po_quantity: 6000, received_quantity: 6000, pending_quantity: 0 },
  { po_id: "po-54", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-02-16", po_number: "4800001811", supplier_name: "PRIME LOGITECH INDUSTRY", material_id: "m-12", material_name: "PJ2 JOINT", uom: "SET", po_quantity: 3000, received_quantity: 3000, pending_quantity: 0 },
  { po_id: "po-55", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-02-13", po_number: "PO-2026-038", supplier_name: "Vikas Industrial Supplies", material_id: "m-18", material_name: "SS PIPE", uom: "MTR", po_quantity: 2000, received_quantity: 2000, pending_quantity: 0 },
  { po_id: "po-56", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-02-10", po_number: "PO-2026-037", supplier_name: "Precision Tools Co", material_id: "m-23", material_name: "END CAP", uom: "PCS", po_quantity: 2500, received_quantity: 2500, pending_quantity: 0 },
  { po_id: "po-57", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-02-07", po_number: "PO-2026-036", supplier_name: "Star Fasteners Ltd", material_id: "m-3", material_name: "40 TYPE A1 JOINT", uom: "PCS", po_quantity: 1500, received_quantity: 1500, pending_quantity: 0 },
  { po_id: "po-58", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-pgtl", plant_name: "PGTL Plant", po_date: "2026-02-04", po_number: "PO-2026-035", supplier_name: "Apex Hardware Corp", material_id: "m-6", material_name: "80 TYPE B2 JOINT", uom: "PCS", po_quantity: 1300, received_quantity: 1300, pending_quantity: 0 },
  { po_id: "po-59", location_id: "loc-bhiwadi", location_name: "Bhiwadi", plant_id: "plant-bhi-ngm", plant_name: "NGM Plant", po_date: "2026-02-02", po_number: "PO-2026-034", supplier_name: "Precision Tools Co", material_id: "m-20", material_name: "6X2 PU WHEEL FIXED", uom: "PCS", po_quantity: 450, received_quantity: 450, pending_quantity: 0 }
];
