/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFabricationRouteImport } from './routes/_authenticated/fabrication'
import { Route as AuthenticatedGapRouteImport } from './routes/_authenticated/gap'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedPurchaseRouteImport } from './routes/_authenticated/purchase'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedMastersDepartmentsRouteImport } from './routes/_authenticated/masters/departments'
import { Route as AuthenticatedMastersLocationsRouteImport } from './routes/_authenticated/masters/locations'
import { Route as AuthenticatedMastersMaterialsRouteImport } from './routes/_authenticated/masters/materials'
import { Route as AuthenticatedMastersProductsRouteImport } from './routes/_authenticated/masters/products'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFabricationRoute =
  AuthenticatedFabricationRouteImport.update({
    id: '/fabrication',
    path: '/fabrication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGapRoute = AuthenticatedGapRouteImport.update({
  id: '/gap',
  path: '/gap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseRoute = AuthenticatedPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMastersDepartmentsRoute =
  AuthenticatedMastersDepartmentsRouteImport.update({
    id: '/masters/departments',
    path: '/masters/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersLocationsRoute =
  AuthenticatedMastersLocationsRouteImport.update({
    id: '/masters/locations',
    path: '/masters/locations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersMaterialsRoute =
  AuthenticatedMastersMaterialsRouteImport.update({
    id: '/masters/materials',
    path: '/masters/materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersProductsRoute =
  AuthenticatedMastersProductsRouteImport.update({
    id: '/masters/products',
    path: '/masters/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/fabrication': typeof AuthenticatedFabricationRoute
  '/gap': typeof AuthenticatedGapRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/purchase': typeof AuthenticatedPurchaseRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/masters/locations': typeof AuthenticatedMastersLocationsRoute
  '/masters/materials': typeof AuthenticatedMastersMaterialsRoute
  '/masters/products': typeof AuthenticatedMastersProductsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/fabrication': typeof AuthenticatedFabricationRoute
  '/gap': typeof AuthenticatedGapRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/purchase': typeof AuthenticatedPurchaseRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/masters/locations': typeof AuthenticatedMastersLocationsRoute
  '/masters/materials': typeof AuthenticatedMastersMaterialsRoute
  '/masters/products': typeof AuthenticatedMastersProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/fabrication': typeof AuthenticatedFabricationRoute
  '/_authenticated/gap': typeof AuthenticatedGapRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/purchase': typeof AuthenticatedPurchaseRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/_authenticated/masters/locations': typeof AuthenticatedMastersLocationsRoute
  '/_authenticated/masters/materials': typeof AuthenticatedMastersMaterialsRoute
  '/_authenticated/masters/products': typeof AuthenticatedMastersProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fabrication'
    | '/gap'
    | '/inventory'
    | '/purchase'
    | '/reports'
    | '/users'
    | '/masters/departments'
    | '/masters/locations'
    | '/masters/materials'
    | '/masters/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/fabrication'
    | '/gap'
    | '/inventory'
    | '/purchase'
    | '/reports'
    | '/users'
    | '/'
    | '/masters/departments'
    | '/masters/locations'
    | '/masters/materials'
    | '/masters/products'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/fabrication'
    | '/_authenticated/gap'
    | '/_authenticated/inventory'
    | '/_authenticated/purchase'
    | '/_authenticated/reports'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/masters/departments'
    | '/_authenticated/masters/locations'
    | '/_authenticated/masters/materials'
    | '/_authenticated/masters/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fabrication': {
      id: '/_authenticated/fabrication'
      path: '/fabrication'
      fullPath: '/fabrication'
      preLoaderRoute: typeof AuthenticatedFabricationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gap': {
      id: '/_authenticated/gap'
      path: '/gap'
      fullPath: '/gap'
      preLoaderRoute: typeof AuthenticatedGapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase': {
      id: '/_authenticated/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof AuthenticatedPurchaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/departments': {
      id: '/_authenticated/masters/departments'
      path: '/masters/departments'
      fullPath: '/masters/departments'
      preLoaderRoute: typeof AuthenticatedMastersDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/locations': {
      id: '/_authenticated/masters/locations'
      path: '/masters/locations'
      fullPath: '/masters/locations'
      preLoaderRoute: typeof AuthenticatedMastersLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/materials': {
      id: '/_authenticated/masters/materials'
      path: '/masters/materials'
      fullPath: '/masters/materials'
      preLoaderRoute: typeof AuthenticatedMastersMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/products': {
      id: '/_authenticated/masters/products'
      path: '/masters/products'
      fullPath: '/masters/products'
      preLoaderRoute: typeof AuthenticatedMastersProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFabricationRoute: typeof AuthenticatedFabricationRoute
  AuthenticatedGapRoute: typeof AuthenticatedGapRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedPurchaseRoute: typeof AuthenticatedPurchaseRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMastersDepartmentsRoute: typeof AuthenticatedMastersDepartmentsRoute
  AuthenticatedMastersLocationsRoute: typeof AuthenticatedMastersLocationsRoute
  AuthenticatedMastersMaterialsRoute: typeof AuthenticatedMastersMaterialsRoute
  AuthenticatedMastersProductsRoute: typeof AuthenticatedMastersProductsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFabricationRoute: AuthenticatedFabricationRoute,
  AuthenticatedGapRoute: AuthenticatedGapRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedPurchaseRoute: AuthenticatedPurchaseRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMastersDepartmentsRoute: AuthenticatedMastersDepartmentsRoute,
  AuthenticatedMastersLocationsRoute: AuthenticatedMastersLocationsRoute,
  AuthenticatedMastersMaterialsRoute: AuthenticatedMastersMaterialsRoute,
  AuthenticatedMastersProductsRoute: AuthenticatedMastersProductsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
